version: '3.6'

services:
  nodered:
    # 2022-01-06: latest läuft nicht auf raspberry pi
    image: ghcr.io/ct-open-source/ctnodered@sha256:6d3b1b0c98986c49b83debfc306b7e02efa6737eb10ea9da79b59f75e46ac028
    volumes:
      - ./data/nodered:/data
      - /etc/localtime:/etc/localtime
    depends_on:
      - mqtt
    restart: always
    logging:
      driver: syslog
    network_mode: "host"
    environment:
      - TZ=Europe/Berlin
    
  mqtt:
    image: "eclipse-mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./data/mqtt:/mosquitto
      - /etc/localtime:/etc/localtime
    restart: always
    logging:
      driver: syslog
    environment:
      - TZ=Europe/Berlin
    
  zigbee:
    image: koenkk/zigbee2mqtt
    volumes:
      - ./data/zigbee:/app/data
      - /run/udev:/run/udev:ro
      - /etc/localtime:/etc/localtime
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
      - "/dev/ttyACM1:/dev/ttyACM1"
    restart: always
    logging:
      driver: syslog
    privileged: true
    ports:
      - 1881:1881
    environment:
      - TZ=Europe/Berlin
